project:
  type: website
  output-dir: docs

website:
  title: IDS
  search: true
  site-url: "https://www.introdata.science/"
  navbar:
    logo: "img/logo.png"
    logo-alt: Course logo with a person icon shuffling five icons one with a bar plot, laptop, data, line plot, and a book. Below the person's icon is a text that reads introdata.science
    pinned: true
    background: whitesmoke
    foreground: "#333333"
    left:
      - href: "index.qmd"
        text: "{{< fa home >}} Home"      
      - href: "people.qmd"
        text: "{{< fa chalkboard-teacher >}} People"
      - href: "policies.qmd"
        text: "{{< fa gavel >}} Policies"
      - href: "schedule.qmd"
        text: "{{< fa calendar >}} Schedule"
      - href: "tools.qmd"
        text: "{{< fa toolbox >}} Tools"
      - href: "resources.qmd"
        text: "{{< fa medal >}} Resources"
    right:
    - icon: github
      href: "{{< var course.github-org >}}"
      aria-label: "GitHub Organization"
    - icon: robot
      href: "{{< var course.classchat >}}"
      aria-label: "Class Chat"
    - icon: patch-question
      href: "{{< var course.discussion >}}"
      aria-label: "Discussion"
    - icon: calculator
      href: "{{< var course.lms >}}"
      aria-label: "Gradebook"
    - icon: bar-chart-steps
      href: "{{< var course.gradescope >}}"
      aria-label: "Gradescope"
  
  
  page-footer:
      center: 
        - text: 	"&copy; {{< var course.year >}} <a href=\" {{< var instructor.website >}} \">{{< var instructor.name >}} </a> <br> <a href=\" https://creativecommons.org/licenses/by-nc-sa/4.0/\"> CC BY-NC-SA 4.0 </a>"
        
format:
  html:
    theme: cosmo
    css: style.css
    toc: true
    include-after-body: plausible.html



