
```{r}
#| message: false
#| echo: false
library(tidyverse)
```

In addition to what is shown on this table, there are weekly homework assignments in your personal GitHub repos.

```{r}
#| echo: false
## Course specifics

slides_repo <- "https://stats6-sp26.github.io/slides/"
gradescope <- "https://www.gradescope.com/courses/1287917"

```


```{r}
#| echo: false
#| message: false
readr::read_csv(here::here("specific-content/schedule.csv")) |> 
  mutate(
    reading = if_else(
      is.na(reading), 
      paste0(fontawesome::fa("book", fill = "#e6ddd1")),
      paste0(
        "[", 
        fontawesome::fa("book"), 
        "]",
        "(specific-content/readings/", 
        reading, 
        ")"
        )
      ),
    slides = if_else(
      is.na(slides), 
      paste0(fontawesome::fa("laptop", fill = "#e6ddd1")),
      paste0(
        "[", 
        fontawesome::fa("laptop"), 
        "]",
        "(",
        slides_repo, 
        slides, 
        ")"
        )
      ),
      assessment = case_when(
      is.na(assessment) ~ paste0(fontawesome::fa("list-check", fill = "#e6ddd1")),
      grepl("qmd", assessment) ~ paste0(
        "[", 
        fontawesome::fa("list-check"), 
        "]",
        "(specific-content/assessment/", 
        assessment, 
        ")"
        ),
      TRUE ~ paste0(
        "[", 
        fontawesome::fa("list-check"), 
        "]",
        "(",
        gradescope, 
        "/assignments/",
        assessment, 
        ")"
        )
      ),
     other = if_else(
      is.na(other), 
      paste0(fontawesome::fa("note-sticky", fill = "#e6ddd1")),
      paste0(
        "[", 
        fontawesome::fa("note-sticky"), 
        "]",
        "(",
        other, 
        ")"
        )
      )
  ) |> 
  knitr::kable() 
```

